# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67d6862feaceb5e3417068229ddd58facf6be221cd58ea073ce885e704f7328d2d09bbe1fc29e64b2351eb67b6e30b4784ee06e60d76bba1dcc1029eeb91ef06

test:
  secret_key_base: a382a096a4f9de69acd345a878c19d9597623503953c04cb3c614642c250cc5cd21fe9e7d2bef359e64fca070ce4a90ad4cb93be640b56d9293d74743d826621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
